name: Mainflow
on:
  push:
    branches: [master, main]
jobs:
  build-and-codechecks:
    name: build and run codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yar
        run: |
          yarn install
          yarn build
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
